[package]
name = "bevy_roguelike"
version = "0.6.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
rand = "0.10.1"

[dependencies.bevy]
version = "0.19"
default-features = false
features = ["std", "bevy_render", "bevy_winit", "x11", "bevy_scene", "bevy_log", "bevy_state"]

[dependencies.bevy_ascii_terminal]
version = "0.19"

[dependencies.adam_fov_rs]
version = "0.5"

[dependencies.sark_pathfinding]
git = "https://github.com/sarkahn/sark_pathfinding_rs"
rev = "ca8bc9f93e06bf96630ac11bf8ed78d82329f2e2"


[profile.release]
opt-level = 's'
lto = true
